Controllers/CategoryController.cs
using Microsoft.AspNetCore.Mvc;
using MvcTeste.Data;
using MvcTeste.Models;

namespace MvcTeste.Controllers
{
    public class CategoryController : Controller
    {
        private readonly ApplicationDbContext _db;

        //carregando Banco de dados como uma varivel _db
        public CategoryController(ApplicationDbContext db)
        {
            _db = db;
        }
        //listando do banco de dados
        public IActionResult Index()
        {
            List<Category> objCategoryList = _db.Categories.ToList();
            return View(objCategoryList);
        }

        
        public IActionResult Create()
        {
            return View();
        }

        //Metodo do tipo httpPost que salva um objeto de um formulario
        [HttpPost]
        public IActionResult Create(Category obj)
        {
            if(obj.Name == obj.DisplayOrder.ToString())
            {
                ModelState.AddModelError("name", "The Display order cannot exactly match the Name.");
            }

            if (obj.Name.ToLower() == "teste")
            {
                ModelState.AddModelError("", "test is an invalid value");
            }

            if (ModelState.IsValid)
            {
                _db.Categories.Add(obj);
                _db.SaveChanges();
                TempData["success"] = "Category created successfully";
                return RedirectToAction("Index", "Category");
            }
            return View();
        }


        public IActionResult Edit(int? id)
        {
            if(id == null || id == 0)
            {
                return NotFound();
            }
            Category? categoryFromDb = _db.Categories.Find(id);

            //outros metodos para procurar um id
            //FisrtOrDefault funciona também para outros atributos alem da chave primaria
            //Category? categoryFromDb1 = _db.Categories.FirstOrDefault(u => u.CategoryId == id);
            //Category? categoryFromDb2 = _db.Categories.Where(u => u.CategoryId == id).FirstOrDefault();

            if (categoryFromDb == null)
            {
                return NotFound();
            }

            return View(categoryFromDb);
        }

        //Metodo do tipo httpPost que salva um objeto de um formulario
        [HttpPost]
        public IActionResult Edit(Category obj)
        {
            if (ModelState.IsValid)
            {
                if (ModelState.IsValid)
                {
                    _db.Categories.Update(obj);
                    _db.SaveChanges();
                    TempData["success"] = "Category edited successfully";
                    return RedirectToAction("Index");
                }
                return View(obj);
            }
            return View();
        }

        public IActionResult Delete(int? id)
        {
            if (id == null || id == 0)
            {
                return NotFound();
            }
            Category? categoryFromDb = _db.Categories.Find(id);

            if (categoryFromDb == null)
            {
                return NotFound();
            }

            return View(categoryFromDb);
        }

        //Metodo do tipo httpPost que salva um objeto de um formulario
        [HttpPost, ActionName("Delete")]

        public IActionResult DeletePost(int? id)
        {
            Category obj = _db.Categories.Find(id);

            if(obj == null)
            { 
                return NotFound(); 
            }

            _db.Categories.Remove(obj);

            _db.SaveChanges();
            TempData["success"] = "Category deleted successfully";
            return RedirectToAction("Index");
        }
    }
}

Controllers/HomeController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using MvcTeste.Models;

namespace MvcTeste.Controllers;

public class HomeController : Controller
{
    private readonly ILogger<HomeController> _logger;

    public HomeController(ILogger<HomeController> logger)
    {
        _logger = logger;
    }

    public IActionResult Index()
    {
        return View();
    }

    public IActionResult Privacy()
    {
        return View();
    }

    public IActionResult Pagina()
    {
        return View();
    }

    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public IActionResult Error()
    {
        return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
    }
}

Controllers/PaginaDoisController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

namespace MvcTeste.Controllers
{
    public class PaginaDoisController : Controller
    {
        // GET: PaginaDoisController
        public ActionResult PagMvc()
        {
            return View();
        }

    }
}

Views/Category/Create.cshtml
@model Category

<div class="card shadow border-0 mt-4">
	<div class="card-header bg-secondary bg-gradient ml-0 py-3">
		<div class="row">
			<div class="col-12 text-center">
				<h2 class="text-white py-2">Create Category</h2>
			</div>
		</div>
	</div>
	<div class="card-body p-4">
		<form method="post">
			<div class="border p-3">
				<!--<div asp-validation-summary="All"></div>-->
				<div asp-validation-summary="ModelOnly"></div>
				<div class="form-floating py-2 col-12">
					<input type="text" asp-for="Name" class="form-control shadow border-0"/>
					<label asp-for="Name" class="ms-2"></label>
					<span asp-validation-for="Name" class="text-danger"></span>
				</div>
				<div class="form-floating py-2 col-12 mt-4">
					<input type="number" asp-for="DisplayOrder" class="form-control shadow border-0" />
					<label asp-for="DisplayOrder" class="ms-2"></label>
					<span asp-validation-for="DisplayOrder" class="text-danger"></span>
				</div>
				<div class="row pt-4">
					<div class="col-6 col-md-3">
						<button type="submit" class="btn btn-primary form-control">Create</button>
					</div>
					<div class="col-6 col-md-3">
						<a asp-controller="Category" asp-action="Index" class="btn btn-outiline-primary border form-control">Back to List</a>
					</div>
				</div>


			</div>
		</form>
	</div>
</div>



@section Scripts {
	@{
		<partial name="_ValidationScriptsPartial"/>
	}
}

Views/Category/Delete.cshtml
@model Category


<div class="card shadow border-0 mt-4">
	<div class="card-header bg-secondary bg-gradient ml-0 py-3">
		<div class="row">
			<div class="col-12 text-center">
				<h2 class="text-white py-2">Delete a Category</h2>
			</div>
		</div>
	</div>
	<div class="card-body p-4">
		<form method="post">
			<div class="border p-3 mt-4">
				<div class="row p-2">
				</div>
				<input type="hidden" asp-for="CategoryId" disabled />
				<!--<div asp-validation-summary="All"></div>-->
				<div asp-validation-summary="ModelOnly"></div>
				<div class="form-floating py-2 col-12">
					<input type="text" asp-for="Name" class="form-control shadow border-0" disabled/>
					<label asp-for="Name" class="ms-2"></label>
					<span asp-validation-for="Name" class="text-danger"></span>
				</div>
				<div class="form-floating py-2 col-12 mt-4">
					<input type="number" asp-for="DisplayOrder" class="form-control shadow border-0" disabled/>
					<label asp-for="DisplayOrder" class="ms-2"></label>
					<span asp-validation-for="DisplayOrder" class="text-danger"></span>
				</div>
				<div class="row pt-4">
					<div class="col-6 col-md-3">
						<button type="submit" class="btn btn-danger form-control">Delete</button>
					</div>
					<div class="col-6 col-md-3">
						<a asp-controller="Category" asp-action="Index" class="btn btn-outiline-secondary form-control">Back to List</a>
					</div>
				</div>


			</div>
		</form>
	</div>
</div>

Views/Category/Edit.cshtml
@model Category

<div class="card shadow border-0 mt-4">
	<div class="card-header bg-secondary bg-gradient ml-0 py-3">
		<div class="row">
			<div class="col-12 text-center">
				<h2 class="text-white py-2">Edit Category</h2>
			</div>
		</div>
	</div>
	<div class="card-body p-4">

		<form method="post">
			<div class="border p-3 mt-4">
				<div class="row p-2">
				</div>

				@*
			Campo oculto necessario para o Id ser passado e assim nao criar
			numa nova instancia no Banco de dados e sim alterar uma ja existente
				*@
				<input type="hidden" asp-for="CategoryId" />
				<!--<div asp-validation-summary="All"></div>-->
				<div asp-validation-summary="ModelOnly"></div>
				<div class="form-floating py-2 col-12">
					<input type="text" asp-for="Name" class="form-control shadow border-0" />
					<label asp-for="Name" class="ms-2"></label>
					<span asp-validation-for="Name" class="text-danger"></span>
				</div>
				<div class="form-floating py-2 col-12 mt-4">
					<input type="number" asp-for="DisplayOrder" class="form-control shadow border-0" />
					<label asp-for="DisplayOrder" class="ms-2"></label>
					<span asp-validation-for="DisplayOrder" class="text-danger"></span>
				</div>
				<div class="row">
					<div class="col-6 col-md-3">
						<button type="submit" class="btn btn-primary form-control">Update</button>
					</div>
					<div class="col-6 col-md-3">
						<a asp-controller="Category" asp-action="Index" class="btn btn-outiline-secondary form-control">Back to List</a>
					</div>
				</div>
			</div>
		</form>
	</div>
</div>


@section Scripts {
	@{
				<partial name="_ValidationScriptsPartial"/>
	}
}

Views/Category/Index.cshtml
@model List<Category>

<div class="card shadow border-0 mt-4">
    <div class="card-header bg-secondary bg-gradient ml-0 py-3">
        <div class="row">
            <div class="col-12 text-center">
                <h2 class="text-white py-2">Category List</h2>
            </div>
        </div>
    </div>
    <div class="card-body p-4">
        <div class="container">
            <div class="row pt-4 pb-4">
                <div class="col-6">
                </div>
                <div class="col-6 text-end">
                    <a asp-controller="Category" asp-action="Create" class="btn btn-primary"><i class="bi bi-plus-square"></i> Add Category</a>
                </div>
            </div>

            <table class="table table-bordered table-striped">
                <thead>
                    <tr>
                        <th>
                            Category Name
                        </th>
                        <th>
                            Display Order
                        </th>
                    </tr>
                </thead>

                <tbody>
                    <!--Lista de objetos puxadas do banco de dados-->
                    @foreach (var obj in Model.OrderBy(u => u.DisplayOrder))
                    {
                        <tr>
                            <td>@obj.Name</td>
                            <td>@obj.DisplayOrder</td>
                            <td>
                                <div class="w-75 btn-group" role="group">
                                    <a asp-controller="Category" asp-action="Edit" asp-route-id="@obj.CategoryId" class="btn btn-primary mx-2">
                                        <i class="bi bi-pencil-square"></i> Edit
                                    </a>
                                    <a asp-controller="Category" asp-action="Delete" asp-route-id="@obj.CategoryId" class="btn btn-danger mx-2">
                                        <i class="bi bi-trash3-fill"></i> Delete
                                    </a>
                                </div>
                            </td>
                        </tr>
                    }
                </tbody>
            </table>
        </div>
    </div>
</div>

Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://learn.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Views/Home/Pagina.cshtml
  <div class="container col-sm-8 col-md-6">
    <main>
        <div class="text-center mt-4">
          <h1>Sua Plataforma de Reciclagem Metalúrgica</h1>
        </div>

        <div class="container">
          <div class="row align-items-center">
            <h2>Sobre Nós</h2>
            <p class="col-md-7 ">
              Nossa plataforma visa fomentar a economia circular, promovendo o reaproveitamento desses materiais e, assim, contribuindo para a redução do impacto ambiental. Buscamos minimizar a poluição, preservando os ecossistemas terrestres e protegendo a fauna e a flora que dependem de um ambiente saudável.
            </p>
            
            <img src="vendor/bs5.3.3/imgs/DesenhoMetalurgia01.jpg" alt="metalurgia ilustrada" class="img-fluid col-md-5 rounded-5 img-custom float">


            <img src="vendor/bs5.3.3/imgs/Metalurgia02.jpg" alt="metalurgia ilustrada" class="img-fluid col-md-5 rounded-5 img-custom float mt-5 mb-2">
            <p class="col-md-7">
              O desenvolvimento do projeto segue a metodologia de Prototipação, que nos permite iterar continuamente e ajustar a plataforma conforme o feedback dos usuários. Ao longo do processo, temos a oportunidade de integrar conhecimentos adquiridos em diferentes disciplinas e aplicar práticas ágeis, criando uma solução prática e alinhada com as necessidades reais dos nossos usuários.
            </p>

            <p class="mt-3">
                Com este projeto, almejamos não só atender às demandas de uma indústria em crescimento, mas também fazer a nossa parte na construção de um futuro mais responsável e sustentável para todos.
            </p>
          </div>     
        </div>

        <div class="d-flex justify-content-center">
          <a href="cadastro.html"><button class="btn btn-warning mb-3 justify-content-center btn-login">Cadastro</button></a>
        </div>

        <a id="sobrenos"></a>
        <div class="container">
          <div class="row align-items-center">
            <h2>Sobre Nós</h2>
            <p class="col-md-6">
                Somos um grupo de alunos do curso de Desenvolvimento de Software Multiplataforma da Fatec Matão Luiz Marchesan, comprometidos com a criação de soluções tecnológicas que contribuem para a sustentabilidade e preservação do meio ambiente. Nosso projeto foi inspirado pelos Objetivos de Desenvolvimento Sustentável da ONU, em particular os relacionados ao "Consumo e Produção Responsável" e "Vida Terrestre". Ao identificar o impacto negativo do descarte inadequado de resíduos metálicos nas empresas, decidimos desenvolver uma plataforma digital que conecta empresas metalúrgicas que necessitam de metais a empresas que descartam resíduos metálicos.
            </p>
            <img src="vendor/bs5.3.3/imgs/img_metalurgia02.jpg" alt="" class="img-fluid img-custom rounded-5 shadow-lg">
          </div>     
        </div>


        <div class="container mt-2">
          <div class="row align-items-center">
            <h2>Se interessou ? Cadastre-se</h2>
            <div class="d-flex justify-content-center mt-3">
              <a href="cadastro.html"><button class="btn btn-warning mb-3 justify-content-center btn-login">Cadastro</button></a>
            </div>
          </div>     
        </div>
      
    </main>
  </div>

Views/PaginaDois/PagMvc.cshtml
@{
    ViewData["Title"] = "PAGINA NOVA";
}

<h1>PAGINA CRIADA EM OUTRO CONTROLADOR</h1>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - MvcTeste</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
    <link rel="stylesheet" href="~/MvcTeste.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/css/toastr.css">
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-primary border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">MvcTeste</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-white" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-white" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-white" asp-area="" asp-controller="Home" asp-action="Pagina">Pagina Nova</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-white" asp-area="" asp-controller="PaginaDois" asp-action="PagMvc">Pagina Nova</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-white" asp-area="" asp-controller="Category" asp-action="Index">Category</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            <partial name="_Notification" />
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer bg-primary text-mute">
        <div class="container text-center text-light">
            &copy; 2025 - MvcTeste - <i class="bi bi-laptop"></i><a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Views/Shared/_Notification.cshtml
@if (TempData["success"] != null)
{
    <script src="~/lib/jquery/dist/jquery.min.js"> </script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/js/toastr.min.js"></script>

    <script type="text/javascript">
        toastr.success('@TempData["success"]');
        toaster.success('DALE');
    </script>

    
}

@if (TempData["error"] != null)
{
    <script src="~/lib/jquery/dist/jquery.min.js"> </script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/js/toastr.min.js"></script>

    <script type="text/javascript">
        toastr.error('@TempData["error"]');
    </script>
}